apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-create-db
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:5.7
        command:
          - bash
          - "-c"
          - |
            mysql -u springuser -pThePassword -h mysql \
            -e "show databases"

      restartPolicy: Never
  completions: 1
